### ISSUE TITLE
Collaboration invitation

### ISSUE THREAD

**Issue by thesunlover** [abdi0987/ViaJS#4]
Hello, Abdi
Recently I saw your repository here and decided to use it.
I also expanded the functionality of the library.
Now it can work with many pieces of code spread on different html files.
Documentation needs more examples now as well

**Comment by abdi0987** [comment]
Sorry for the very late response! I've been very busy. Reviewing your contributions right now thanks!

**Comment by abdi0987** [comment]
Hey! Reviewed your changes they were awesome thanks for your help. Merged your pull request.
