### ISSUE TITLE
double click

### ISSUE THREAD

**Issue by abdi0987** [abdi0987/ViaJS#7]
when you click on the a tag with a via-link attribute twice it tries to go to a page instead of has for example

when you click on home link in the demo the link looks like this http://viajs.surge.sh/#home

but when you click on the home link again the link looks like this  http://viajs.surge.sh/home
it tries to go to the /home instead of /#home therefore its redirected to a 404 page.

**Comment by abdi42** [comment]
fixed! changed a tag href atrribute to via-href
